version: '3.8'

services:
  airflow:
    build:
      context: .
      dockerfile: airflow.Dockerfile
    image: custom_airflow_no_mysql
    container_name: airflow
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor        
      AIRFLOW__CORE__FERNET_KEY: 'yAqUPWYfQLu4_5ZZ4Q3gsbBXMxOAxuUCI43IgC0GV70='
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
      AIRFLOW__API__AUTH_BACKENDS: 'airflow.api.auth.backend.basic_auth'
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
    ports:
      - "8080:8080"
    command: >
      bash -c "
        airflow db reset -y &&
        airflow db upgrade &&
        airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com &&
        airflow scheduler & exec airflow webserver
      "
    restart: always
